### ISSUE TITLE
Make J-road available in the Maven central repository

### ISSUE THREAD

**Issue by informatik01** [nortal/j-road#2]
It would be much more convenient to be able to add J-road library or some of its sub-components as a dependency in a POM without messing around with _system_ scope or deploying it yourself to some repository etc. 

So making J-road available in the Maven central repository or at least providing some other repository location would be a **big plus**.

**Comment by ldabul** [comment]
Enabled by this commit https://github.com/nortal/j-road/commit/eeb75031baa88b14eadc7c5cc22de237a21530a2
